### ISSUE TITLE
password fields not contained in form

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/webui#4]
Chrome devtools console shows the following warnings when Alice WebUI fires up. this is on 1.0.0-b5

![image](https://user-images.githubusercontent.com/4626024/106823302-6cd21180-66cc-11eb-9a6c-c59d615c9e31.png)

**Comment by Psychokiller1888** [comment]
Yeah, I know, the thing is, none of the fields are in any forms, I do not use forms for them to prevent page reloads and other background stuff related to forms, like auto completion etc etc
